### ISSUE TITLE
[Feature] Add support for "pods" architecture

### ISSUE THREAD

**Issue by tehhowch** [rajasegar/ember-plantuml#1]
```
$ npx ember-plantuml
Ember Plant UML
Ember PlantUML Server listening to http://localhost:56749
Error: ENOENT: no such file or directory, lstat '/Users/me/apps/monorepo/packages/package/app/components'
    at Object.realpathSync (fs.js:1728:7)
    at _walkSync (/Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/node_modules/walk-sync/index.js:108:25)
    at walkSync (/Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/node_modules/walk-sync/index.js:20:12)
    at /Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/server/index.js:28:24
    at Layer.handle [as handle_request] (/Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/node_modules/express/lib/router/layer.js:95:5)
    at /Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/me/.npm/_npx/53794/lib/node_modules/ember-plantuml/node_modules/express/lib/router/index.js:335:12)
```
Inside `app` directory:
```
$ ls app
app.js helpers index.html initializers mixins models pods router.js services styles
```

inside `app/pods` directory:
```$ ls app/pods/
application application-loading components someRouteName login
```

**Comment by rajasegar** [comment]
Is there a way to identify pods layout in a project? Can you please point to me a sample repo or any guides how the pods layout works?

**Comment by tehhowch** [comment]
A simple heuristic could be:

1) has addon folder -> component root is `addon`
2) root does not contain `components` but does contain `pods` -> component root = `app/pods/`
3) `usePods` .ember-cli option is true -> components are in `app/pods/`

Note that pods components are differentiated by pathname, not basename - they're all `component.js` and `template.hbs`, e.g. `app/pods/components/my-app-input/component.js`

Addons aren't _supposed_ to use pods, but they sure can.

**Comment by shamrt** [comment]
Here's the official docs for pod layout: https://cli.emberjs.com/release/advanced-use/project-layouts/#podslayout
